# .github/workflows/use-my-action.yml
name: Use My TypeScript Action

on:
  workflow_dispatch:
    inputs:
      source-directory:
        description: 'env'
        required: true
        type: string
      debug-mode:
        description: '重新下载'
        required: true
        type: boolean
      num-count:
        description: '数量'
        required: true
        type: number
      environment:
        description: 'Select deployment environment'
        required: true
        type: choice
        options:
          - staging
          - production
          - development
      region:
        description: 'Select AWS region'
        required: false
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
          - us-west-2
          - eu-central-1        
        
        

jobs:
  test:
    environment: ${{ inputs.source-directory }} 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: 使用自定义 checkout Action
        id: checkout
        uses: houjiayou888/actions/codearts-checkout@dev
        with:
          hello-world: ${{ inputs.source-directory }}
      
