# .github/workflows/use-my-action.yml
name: Use My TypeScript Action

on:
  workflow_dispatch:
    inputs:
      source-directory:
        description: 'env'
        required: true
        type: string
      debug-mode:
        description: '重新下载'
        required: true
        type: boolean
      num-count:
        description: '数量'
        required: true
        type: number
      environment:
        description: 'Select deployment environment'
        required: true
        type: choice
        options:
          - staging
          - production
          - development
      region:
        description: 'Select AWS region'
        required: false
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
          - us-west-2
          - eu-central-1        
        
        

jobs:
  test:
    environment: ${{ inputs.source-directory }} 
    runs-on: ubuntu-latest
    steps:
      - name: 使用自定义checkout
        uses: houjiayou888/actions/codearts-checkout@dev
        with:
          repository: 'https://gitee.com/perfbenchmark/tone-agent-proxy.git'
          ref_type: 'branch'
          ref_value:  'v1.11.0'
          target_path: '.'
          recurse_submodules: false
          custom_depth: ''
          enable_lfs: false
      - name: 使用自定义 setupmaven Action
        id: setupmaven
        uses: houjiayou888/actions/codearts-setup-maven@dev
        with:
          maven_version: '3.9.6'
      - name: 使用自定义 mavenbuild Action
        id: mavenbuild
        uses: houjiayou888/actions/codearts-maven-build@dev
        with:
          maven-command: 'mvn package -Dmaven.test.skip=true -U -e -X -B'
          continue-on-failure: true
