# .github/workflows/use-my-action.yml
name: Use My TypeScript Action

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Project ID'
        required: true
      token:
        description: 'Token'
        required: true        
        
jobs:
  test:
    environment: ${{ inputs.source-directory }} 
    runs-on: ubuntu-latest
    steps:
      - name: 使用自定义checkout
        uses: houjiayou888/actions/codearts-checkout@dev
        with:
          token: ${{ inputs.token }}
          project_id: ${{ inputs.project_id }}
          repository: 'https://gitee.com/perfbenchmark/tone-agent-proxy.git'
          ref_type: 'branch'
          ref_value:  'v1.11.0'
          target_path: '.'
          recurse_submodules: false
          custom_depth: ''
          enable_lfs: false
      - name: 使用自定义 setupmaven Action
        id: setupmaven
        uses: houjiayou888/actions/codearts-setup-maven@dev
        with:
          maven_version: '3.9.6'
      - name: 使用自定义 mavenbuild Action
        id: mavenbuild
        uses: houjiayou888/actions/codearts-maven-build@dev
        with:
          maven-command: 'mvn package -Dmaven.test.skip=true -U -e -X -B'
          continue-on-failure: true
